# Generated by Django 5.0.1 on 2024-11-08 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submodulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_nac', models.DateField()),
                ('altura', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pierna_habil', models.CharField(choices=[('I', 'Izquierda'), ('D', 'Derecha'), ('A', 'Ambas')], max_length=10)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submodulos.pais')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submodulos.puesto')),
            ],
        ),
    ]
