# Generated by Django 5.0.1 on 2024-11-26 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_telefono',
            field=models.CharField(help_text='Ejemplo: 0991234567 para móvil o 022345678 para fijo.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono ecuatoriano válido (móvil o fijo).', regex='^(?:09\\d{8}|0[2-7]\\d{7})$')]),
        ),
    ]
