# Generated by Django 5.0.1 on 2024-11-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_usuario_numero_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cambio_pass',
            field=models.BooleanField(default=True),
        ),
    ]
