# Generated by Django 5.0.1 on 2024-11-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_usuario_cambio_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contador_intentos',
            field=models.IntegerField(default=0),
        ),
    ]
