# Generated by Django 5.0.1 on 2024-11-15 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion_total', models.FloatField(blank=True, null=True)),
                ('valoracion_tiro', models.FloatField(blank=True, null=True)),
                ('valoracion_pase', models.FloatField(blank=True, null=True)),
                ('valoracion_velocidad', models.FloatField(blank=True, null=True)),
                ('valoracion_regate', models.FloatField(blank=True, null=True)),
                ('valoracion_defensa', models.FloatField(blank=True, null=True)),
                ('valoracion_fisico', models.FloatField(blank=True, null=True)),
                ('valoracion_reflejos', models.FloatField(blank=True, null=True)),
                ('valoracion_manejo', models.FloatField(blank=True, null=True)),
                ('valoracion_saque', models.FloatField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('hora_actualizacion', models.TimeField(auto_now=True)),
                ('usuario_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jugador')),
            ],
        ),
    ]
