# Generated by Django 5.0.1 on 2024-11-15 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('submodulos', '0004_alter_estadistica_estadistica'),
        ('valoraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoracion',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Valoracion Cabecera', 'verbose_name_plural': 'Valoraciones Cabeceras'},
        ),
        migrations.AddField(
            model_name='valoracion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.jugador'),
        ),
        migrations.CreateModel(
            name='ValoracionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('usuario_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('estadistica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submodulos.estadistica')),
                ('valoracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='valoraciones.valoracion')),
            ],
            options={
                'verbose_name': 'Detalle de Valoración',
                'verbose_name_plural': 'Detalles de Valoración',
            },
        ),
    ]
