# Generated by Django 5.0.1 on 2024-11-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0002_puestocualidad_unique_puesto_cualidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='estadistica',
            field=models.CharField(choices=[('Tiros totales', 'Tiros totales'), ('Tiros al arco', 'Tiros al arco'), ('Goles anotados', 'Goles anotados'), ('Penales ejecutados', 'Penales ejecutados'), ('Penales anotados', 'Penales anotados'), ('Pases totales', 'Pases totales'), ('Pases acertados', 'Pases acertados'), ('Centros totales', 'Centros totales'), ('Centros acertados', 'Centros acertados'), ('Sprint', 'Sprint'), ('Aceleracion', 'Aceleracion'), ('Regates totales', 'Regates totales'), ('Regates exitosos', 'Regates exitosos'), ('Duelos totales', 'Duelos totales'), ('Duelos exitosos', 'Duelos exitosos'), ('Intercepciones intentos', 'Intercepciones intentos'), ('Intercepciones exitosas', 'Intercepciones exitosas'), ('Despejes intentos', 'Despejes intentos'), ('Despejes exitosos', 'Despejes exitosos'), ('Duelos defensivos totales', 'Duelos defensivos totales'), ('Duelos defensivos ganados', 'Duelos defensivos ganados'), ('Salto evaluado', 'Salto evaluado'), ('Distancia recorrida', 'Distancia recorrida'), ('Sprints realizados', 'Sprints realizados'), ('Fuerza explosiva evaluada', 'Fuerza explosiva evaluada'), ('Fuerza isometrica evaluada', 'Fuerza isometrica evaluada'), ('Fuerza resistencia evaluada', 'Fuerza resistencia evaluada'), ('Tiros totales', 'Tiros totales'), ('Tiros bloqueados', 'Tiros bloqueados'), ('Despejes totales', 'Despejes totales'), ('Despejes exitosos', 'Despejes exitosos'), ('Balones atrapados', 'Balones atrapados'), ('Atrapes sin rebote', 'Atrapes sin rebote'), ('Penales recibidos', 'Penales recibidos'), ('Penales atajados', 'Penales atajados'), ('1v1 totales', '1v1 totales'), ('1v1 ganados', '1v1 ganados'), ('Tiros bloqueados', 'Tiros bloqueados'), ('Atajadas criticas', 'Atajadas criticas'), ('Saques largos intentos', 'Saques largos intentos'), ('Saques largos exitosos', 'Saques largos exitosos'), ('Saques cortos intentos', 'Saques cortos intentos'), ('Saques cortos exitosos', 'Saques cortos exitosos')], max_length=128),
        ),
    ]
